# Read in the large polymer (made up of many units)
# If upper- and lowercase of same letter are next to each other, then
# these two disappear

# Read in the data (p for polymer)
p <- read.table("Day_05_Input.txt", stringsAsFactors=F)
p <- as.vector(p[1, 1])

# Define a function to eliminate matches
eliminateMatches <- function(x) {
  lengths <- c(0, nchar(x)) # More useful than unlist(strsplit())
  current.length <- 0 # for the first iteration in while loop
  
  # Possible polymer combinations that will react
  possible <- c(paste0(letters, toupper(letters)), 
                paste0(toupper(letters), letters))
  
  current.iter <- x
  while(lengths[length(lengths)] != lengths[length(lengths) -1]) {
    current.iter <- gsub(pattern=paste(possible, collapse="|"), 
                         x=current.iter, replacement="")
    current.length <- nchar(current.iter)
    lengths <- c(lengths, current.length)
  }
  return(current.length)
}

new.p <- eliminateMatches(x=p)
print(new.p) # Solution to Part 1

################################################################################

# What's the length of shortest polymer generated by removing units of one type?
p.lengths <- rep(NA, length(letters))
for(i in 1:length(letters)) {
  current.pattern <- letters[i]
  message("Working on ", current.pattern)
  current.p <- gsub(pattern=current.pattern, x=p, replacement="", ignore.case=T)
  p.lengths[i] <- eliminateMatches(x=current.p)
}

minimum.length <- min(p.lengths)
print(minimum.length) # Solution to Part 2
